Feat: Render testruns data as JSON instead of HTML for Fern-UI
Guidewire/fern-reporter pull request #69
Opened 2024-05-20 05:05 UTC by gowtham-ra

1. Render ReportTestRunAll data as json instead of HTML.
2. Update README for accessing the Fern-UI dashboard for test results.

2024-05-20 18:20 UTC, anoop2811 requested changes

2024-05-20 18:20 UTC, anoop2811 commented on README.md
> +which provides a visual dashboard for the test results.
Lets leave both options ie. use fern-ui or use the embedded UI. The idea behind this is to foster innovation outside if needed using the apis we have

2024-05-20 18:20 UTC, anoop2811 commented on pkg/api/handlers/handlers.go
Lets add new methods for fern-ui without removing the old code  for static html. I would always leave the embedded here as a one stop shop so as not to depend on many external packages,.

2024-05-31 14:57 UTC, gowtham-ra commented on pkg/api/handlers/handlers.go
Thanks for the feedback. I'll make the changes to support both views.

2024-06-03 06:13 UTC, gowtham-ra commented on pkg/api/handlers/handlers.go
I've made the changes. Now by default reports/testruns return JSON. HTML is available at reports/testruns/html

2024-06-03 17:32 UTC, anoop2811 commented on pkg/api/handlers/handlers.go
I would instead use /api/reports/testruns to indicate the api which returns json and leave reports/testruns as the embedded html

2024-07-04 04:00 UTC, anoop2811 approved these changes

2024-07-04 04:00 UTC, merged

2024-07-04 04:00 UTC, anoop2811 commented
LGTM, thank you for the contribution!